In [157]:
import pandas as pd
import numpy as np

In [158]:
data = pd.read_csv("dataset/googleplaystore.csv")

In [159]:
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [160]:
data.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='object')

In [161]:
da = data['App']
da

0           Photo Editor & Candy Camera & Grid & ScrapBook
1                                      Coloring book moana
2        U Launcher Lite – FREE Live Cool Themes, Hide ...
3                                    Sketch - Draw & Paint
4                    Pixel Draw - Number Art Coloring Book
                               ...
10836                                     Sya9a Maroc - FR
10837                     Fr. Mike Schmitz Audio Teachings
10838                               Parkinson Exercices FR
10839                        The SCP Foundation DB fr nn5n
10840        iHoroscope - 2018 Daily Horoscope & Astrology
Name: App, Length: 10841, dtype: object

In [162]:
len(data)

10841

In [163]:
data.isnull()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,False,False,False,False,False,False,False,False,False,False,False,False,False
10837,False,False,False,False,False,False,False,False,False,False,False,False,False
10838,False,False,True,False,False,False,False,False,False,False,False,False,False
10839,False,False,False,False,False,False,False,False,False,False,False,False,False
10840,False,False,False,False,False,False,False,False,False,False,False,False,False

In [164]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [165]:
#  so rating 1474 values are null 
#  type = 1 are null
#  content rating  1 are null
# current var 8 is null
# android ver 3 is null

# we can drop down the values or alter the values

## first check with drop the values by data.dropna()

In [166]:
df = data
data.dropna()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [167]:
data.dropna().sum()

App               Photo Editor & Candy Camera & Grid & ScrapBook...
Category          ART_AND_DESIGNART_AND_DESIGNART_AND_DESIGNART_...
Rating                                                      39235.6
Reviews           1599678751021564496716717836815137911211388087...
Size              19M14M8.7M25M2.8M5.6M19M29M33M3.1M28M12M20M21M...
Installs          10,000+500,000+5,000,000+50,000,000+100,000+50...
Type              FreeFreeFreeFreeFreeFreeFreeFreeFreeFreeFreeFr...
Price             0000000000000000000000000000000000000000000000...
Content Rating    EveryoneEveryoneEveryoneTeenEveryoneEveryoneEv...
Genres            Art & DesignArt & Design;Pretend PlayArt & Des...
Last Updated      January 7, 2018January 15, 2018August 1, 2018J...
Current Ver       1.0.02.0.01.2.4Varies with device1.11.01.16.1....
Android Ver       4.0.3 and up4.0.3 and up4.0.3 and up4.2 and up...
dtype: object

In [168]:
da = data.dropna()
da.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

# So we removed the null values

In [169]:

data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

# when we analysing the data first we work with numeric data

## lets works with Rating and reviews

In [170]:

## To finding the average of Rating

df=data.dropna() # to drop none values
drating = df['Rating']
# drating
#  sum
s=0
for i in df['Rating']:
    s=s+i
s=int(s)

# to average rating 
avg=s/len(df['Rating']) # total sum / total len
avg = str(avg)
avg[0:4]

'4.19'

In [171]:
# Question 2)    we have to do some operation on equals like

# df['Rating']
c=0;
for i in df['Rating']:
    if(i == 4.5):
        c=c+1;
    else:
        continue

# To how many applications are there of rating 4.5

c



#  Continue the same for all operation like 5.0 , 4.0, 3.5 etc.......

1037

# Lets find with category wise ..............................................

In [172]:
df['Category']

0             ART_AND_DESIGN
1             ART_AND_DESIGN
2             ART_AND_DESIGN
3             ART_AND_DESIGN
4             ART_AND_DESIGN
                ...
10834                 FAMILY
10836                 FAMILY
10837                 FAMILY
10839    BOOKS_AND_REFERENCE
10840              LIFESTYLE
Name: Category, Length: 9360, dtype: object

In [173]:
#  We have to find the unique category

dfUnique  =  df['Category'].unique()
print(dfUnique)
print("there are ",len(dfUnique)," unique category are there")

['ART_AND_DESIGN' 'AUTO_AND_VEHICLES' 'BEAUTY' 'BOOKS_AND_REFERENCE'
 'BUSINESS' 'COMICS' 'COMMUNICATION' 'DATING' 'EDUCATION' 'ENTERTAINMENT'
 'EVENTS' 'FINANCE' 'FOOD_AND_DRINK' 'HEALTH_AND_FITNESS' 'HOUSE_AND_HOME'
 'LIBRARIES_AND_DEMO' 'LIFESTYLE' 'GAME' 'FAMILY' 'MEDICAL' 'SOCIAL'
 'SHOPPING' 'PHOTOGRAPHY' 'SPORTS' 'TRAVEL_AND_LOCAL' 'TOOLS'
 'PERSONALIZATION' 'PRODUCTIVITY' 'PARENTING' 'WEATHER' 'VIDEO_PLAYERS'
 'NEWS_AND_MAGAZINES' 'MAPS_AND_NAVIGATION']
there are  33  unique category are there

In [174]:
#  find how many times each category is present (like Count) 
c=0
for i in df['Category']:
    if (i == 'ART_AND_DESIGN'):
        c=c+1
c

#  so do the operation for all other conditions

61

## lets works with Automatic Process

In [175]:
for name in data['Category'].unique():
    count=0;
    for i in data['Category']:
        if(i==name):
            count=count+1;
        else:
            continue
    print(name,":",count)

ART_AND_DESIGN : 65
AUTO_AND_VEHICLES : 85
BEAUTY : 53
BOOKS_AND_REFERENCE : 231
BUSINESS : 460
COMICS : 60
COMMUNICATION : 387
DATING : 234
EDUCATION : 156
ENTERTAINMENT : 149
EVENTS : 64
FINANCE : 366
FOOD_AND_DRINK : 127
HEALTH_AND_FITNESS : 341
HOUSE_AND_HOME : 88
LIBRARIES_AND_DEMO : 85
LIFESTYLE : 382
GAME : 1144
FAMILY : 1972
MEDICAL : 463
SOCIAL : 295
SHOPPING : 260
PHOTOGRAPHY : 335
SPORTS : 384
TRAVEL_AND_LOCAL : 258
TOOLS : 843
PERSONALIZATION : 392
PRODUCTIVITY : 424
PARENTING : 60
WEATHER : 82
VIDEO_PLAYERS : 175
NEWS_AND_MAGAZINES : 283
MAPS_AND_NAVIGATION : 137
1.9 : 1

## Same for type , Genere, etc....

In [176]:
# TYPE
for name in data['Type'].unique():
    c=0;
    for i in data['Type']:
        if(i==name):
            c=c+1;
    print(name,":",c)

Free : 10039
Paid : 800
nan : 0
0 : 1

In [177]:
# GENERE
for name in data['Genres'].unique():
    c=0;
    for i in data['Genres']:
        if(i==name):
            c=c+1;
    print(name,":",c)

Art & Design : 58
Art & Design;Pretend Play : 2
Art & Design;Creativity : 7
Art & Design;Action & Adventure : 2
Auto & Vehicles : 85
Beauty : 53
Books & Reference : 231
Business : 460
Comics : 59
Comics;Creativity : 1
Communication : 387
Dating : 234
Education;Education : 50
Education : 549
Education;Creativity : 7
Education;Music & Video : 5
Education;Action & Adventure : 6
Education;Pretend Play : 23
Education;Brain Games : 5
Entertainment : 623
Entertainment;Music & Video : 27
Entertainment;Brain Games : 8
Entertainment;Creativity : 3
Events : 64
Finance : 366
Food & Drink : 127
Health & Fitness : 341
House & Home : 88
Libraries & Demo : 85
Lifestyle : 381
Lifestyle;Pretend Play : 1
Adventure;Action & Adventure : 13
Arcade : 220
Casual : 193
Card : 48
Casual;Pretend Play : 31
Action : 365
Strategy : 107
Puzzle : 140
Sports : 398
Music : 22
Word : 29
Racing : 98
Casual;Creativity : 7
Casual;Action & Adventure : 21
Simulation : 200
Adventure : 75
Board : 44
Trivia : 38
Role Playing : 109
Simulation;Education : 3
Action;Action & Adventure : 17
Casual;Brain Games : 13
Simulation;Action & Adventure : 11
Educational;Creativity : 5
Puzzle;Brain Games : 19
Educational;Education : 41
Card;Brain Games : 1
Educational;Brain Games : 6
Educational;Pretend Play : 19
Entertainment;Education : 1
Casual;Education : 3
Music;Music & Video : 3
Racing;Action & Adventure : 20
Arcade;Pretend Play : 1
Role Playing;Action & Adventure : 7
Simulation;Pretend Play : 4
Puzzle;Creativity : 2
Sports;Action & Adventure : 4
Educational;Action & Adventure : 4
Arcade;Action & Adventure : 16
Entertainment;Action & Adventure : 3
Puzzle;Action & Adventure : 5
Strategy;Action & Adventure : 2
Music & Audio;Music & Video : 1
Health & Fitness;Education : 1
Adventure;Education : 2
Board;Brain Games : 15
Board;Action & Adventure : 3
Board;Pretend Play : 1
Casual;Music & Video : 2
Role Playing;Pretend Play : 5
Entertainment;Pretend Play : 2
Video Players & Editors;Creativity : 2
Card;Action & Adventure : 2
Medical : 463
Social : 295
Shopping : 260
Photography : 335
Travel & Local : 257
Travel & Local;Action & Adventure : 1
Tools : 842
Tools;Education : 1
Personalization : 392
Productivity : 424
Parenting : 46
Parenting;Music & Video : 6
Parenting;Education : 7
Parenting;Brain Games : 1
Weather : 82
Video Players & Editors : 173
Video Players & Editors;Music & Video : 3
News & Magazines : 283
Maps & Navigation : 137
Health & Fitness;Action & Adventure : 1
Educational : 37
Casino : 39
Adventure;Brain Games : 1
Trivia;Education : 1
Lifestyle;Education : 1
Books & Reference;Creativity : 1
Books & Reference;Education : 2
Puzzle;Education : 1
Role Playing;Education : 1
Role Playing;Brain Games : 1
Strategy;Education : 1
Racing;Pretend Play : 1
Communication;Creativity : 1
February 11, 2018 : 1
Strategy;Creativity : 1

## So 2 method : deal with Null values (Note: 1st method is remove null values and work on the preprocessing.)

In [178]:
import numpy as np
from sklearn.impute import SimpleImputer

In [179]:
data  = pd.read_csv("dataset/numeric_method1.csv")

In [180]:
data.isnull().sum()

Age                        4
Attrition                  0
DailyRate                  0
Department                 2
DistanceFromHome           3
Education                  0
EmployeeCount              1
EmployeeNumber             1
EnvironmentSatisfaction    0
Gender                     4
HourlyRate                 3
dtype: int64

In [181]:
# dataset = {
#     age:[1,20,3,50,40,90,20,'nan',10,20,30,20,10,15,32,20,20,15]
# }

## We have use sklearn to add sum values to null field for that we use Imputer

##  first we choose the column for which column we want fill the numeric values and string values. 
##     ----- For that we use iloc function basically it works on row and col wise operation
## syntax :
###              iloc[from : end-1,from:end-1]

In [182]:
dataselection=data.iloc[:,0:5]

In [183]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent') # here the missing values = np.nan (it will cj=heck for nan field and fill with most reapted values(we can do operation like mean,median ,std,etc))

In [184]:
dataselection  = imputer.fit_transform(dataselection)

## For category of strings included we used most frequent stratagy other than mean ,mode ,etc..........................................
## for numeric null we use mode,mean, most_frequent,etc.....

In [185]:
dataselection

array([[41.0, 1, 1102, 'Sales', 1.0],
       [49.0, 0, 279, 'Research & Development', 8.0],
       [37.0, 1, 1373, 'Research & Development', 2.0],
       [33.0, 0, 1392, 'Research & Development', 3.0],
       [27.0, 0, 591, 'Research & Development', 2.0],
       [32.0, 0, 1005, 'Research & Development', 2.0],
       [35.0, 0, 1324, 'Research & Development', 3.0],
       [30.0, 0, 1358, 'Research & Development', 24.0],
       [38.0, 0, 216, 'Research & Development', 23.0],
       [36.0, 0, 1299, 'Research & Development', 27.0],
       [35.0, 0, 809, 'Research & Development', 16.0],
       [35.0, 0, 153, 'Research & Development', 15.0],
       [31.0, 0, 670, 'Research & Development', 1.0],
       [34.0, 0, 1346, 'Research & Development', 19.0],
       [28.0, 1, 103, 'Research & Development', 24.0],
       [29.0, 0, 1389, 'Research & Development', 21.0],
       [32.0, 0, 334, 'Research & Development', 5.0],
       [22.0, 0, 1123, 'Research & Development', 16.0],
       [53.0, 0, 1219, 'Research & Development', 2.0],
       [38.0, 0, 371, 'Research & Development', 2.0],
       [24.0, 0, 673, 'Research & Development', 11.0],
       [35.0, 1, 1218, 'Sales', 9.0],
       [34.0, 0, 419, 'Research & Development', 7.0],
       [21.0, 0, 391, 'Research & Development', 15.0],
       [34.0, 1, 699, 'Research & Development', 6.0],
       [53.0, 0, 1282, 'Research & Development', 5.0],
       [32.0, 1, 1125, 'Research & Development', 16.0],
       [42.0, 0, 691, 'Sales', 8.0],
       [44.0, 0, 477, 'Research & Development', 7.0],
       [46.0, 0, 705, 'Sales', 2.0],
       [33.0, 0, 924, 'Research & Development', 2.0],
       [44.0, 0, 1459, 'Research & Development', 10.0],
       [30.0, 0, 125, 'Research & Development', 9.0],
       [39.0, 1, 895, 'Sales', 5.0],
       [24.0, 1, 813, 'Research & Development', 1.0],
       [43.0, 0, 1273, 'Research & Development', 2.0],
       [50.0, 1, 869, 'Sales', 3.0],
       [35.0, 0, 890, 'Sales', 2.0],
       [36.0, 0, 852, 'Research & Development', 5.0],
       [33.0, 0, 1141, 'Sales', 1.0],
       [35.0, 0, 464, 'Research & Development', 4.0],
       [27.0, 0, 1240, 'Research & Development', 2.0],
       [26.0, 1, 1357, 'Research & Development', 25.0],
       [27.0, 0, 994, 'Sales', 8.0],
       [30.0, 0, 721, 'Research & Development', 1.0],
       [41.0, 1, 1360, 'Research & Development', 12.0],
       [34.0, 0, 1065, 'Sales', 23.0],
       [37.0, 0, 408, 'Research & Development', 19.0],
       [46.0, 0, 1211, 'Sales', 5.0],
       [35.0, 0, 1229, 'Research & Development', 8.0],
       [48.0, 1, 626, 'Research & Development', 1.0],
       [28.0, 1, 1434, 'Research & Development', 5.0],
       [44.0, 0, 1488, 'Sales', 1.0],
       [35.0, 0, 1097, 'Research & Development', 11.0],
       [26.0, 0, 1443, 'Sales', 23.0],
       [33.0, 0, 515, 'Research & Development', 1.0],
       [35.0, 0, 853, 'Sales', 18.0],
       [35.0, 0, 1142, 'Research & Development', 23.0],
       [31.0, 0, 655, 'Research & Development', 7.0],
       [37.0, 0, 1115, 'Research & Development', 1.0],
       [32.0, 0, 427, 'Research & Development', 1.0],
       [38.0, 0, 653, 'Research & Development', 29.0],
       [50.0, 0, 989, 'Research & Development', 7.0],
       [59.0, 0, 1435, 'Sales', 25.0],
       [36.0, 0, 1223, 'Research & Development', 8.0],
       [55.0, 0, 836, 'Research & Development', 8.0],
       [36.0, 0, 1195, 'Research & Development', 11.0],
       [45.0, 0, 1339, 'Research & Development', 7.0],
       [35.0, 0, 664, 'Research & Development', 1.0],
       [36.0, 1, 318, 'Research & Development', 9.0],
       [59.0, 0, 1225, 'Sales', 1.0],
       [29.0, 0, 1328, 'Research & Development', 2.0],
       [31.0, 0, 1082, 'Research & Development', 1.0],
       [32.0, 0, 548, 'Research & Development', 1.0],
       [36.0, 0, 132, 'Research & Development', 6.0],
       [31.0, 0, 746, 'Research & Development', 8.0],
       [35.0, 0, 776, 'Sales', 1.0],
       [45.0, 0, 193, 'Research & Development', 6.0],
       [37.0, 0, 397, 'Research & Development', 7.0],
       [46.0, 0, 945, 'Human Resources', 5.0],
       [30.0, 0, 852, 'Research & Development', 1.0],
       [35.0, 0, 1214, 'Research & Development', 1.0],
       [55.0, 0, 111, 'Sales', 1.0],
       [38.0, 0, 573, 'Research & Development', 6.0],
       [34.0, 0, 1153, 'Research & Development', 1.0],
       [56.0, 0, 1400, 'Research & Development', 7.0],
       [23.0, 0, 541, 'Sales', 2.0],
       [51.0, 0, 432, 'Research & Development', 9.0],
       [30.0, 0, 288, 'Research & Development', 2.0],
       [46.0, 1, 669, 'Sales', 9.0],
       [40.0, 0, 530, 'Research & Development', 1.0],
       [51.0, 0, 632, 'Sales', 21.0],
       [30.0, 0, 1334, 'Sales', 4.0],
       [46.0, 0, 638, 'Research & Development', 1.0],
       [32.0, 0, 1093, 'Sales', 6.0],
       [54.0, 0, 1217, 'Research & Development', 2.0],
       [24.0, 0, 1353, 'Sales', 3.0],
       [28.0, 0, 120, 'Sales', 4.0],
       [58.0, 0, 682, 'Sales', 10.0],
       [44.0, 0, 489, 'Research & Development', 23.0],
       [37.0, 1, 807, 'Human Resources', 6.0],
       [32.0, 0, 827, 'Research & Development', 1.0],
       [20.0, 1, 871, 'Research & Development', 6.0],
       [34.0, 0, 665, 'Research & Development', 6.0],
       [37.0, 0, 1040, 'Research & Development', 2.0],
       [59.0, 0, 1420, 'Human Resources', 2.0],
       [50.0, 0, 1115, 'Research & Development', 1.0],
       [25.0, 1, 240, 'Sales', 5.0],
       [25.0, 0, 1280, 'Research & Development', 7.0],
       [22.0, 0, 534, 'Research & Development', 15.0],
       [51.0, 0, 1456, 'Research & Development', 1.0],
       [34.0, 1, 658, 'Research & Development', 7.0],
       [54.0, 0, 142, 'Human Resources', 26.0],
       [24.0, 0, 1127, 'Research & Development', 18.0],
       [34.0, 0, 1031, 'Research & Development', 6.0],
       [37.0, 0, 1189, 'Sales', 3.0],
       [34.0, 0, 1354, 'Research & Development', 5.0],
       [36.0, 0, 1467, 'Sales', 11.0],
       [36.0, 0, 922, 'Research & Development', 3.0],
       [43.0, 0, 394, 'Sales', 26.0],
       [30.0, 0, 1312, 'Research & Development', 23.0],
       [33.0, 0, 750, 'Sales', 22.0],
       [56.0, 1, 441, 'Research & Development', 14.0],
       [51.0, 0, 684, 'Research & Development', 6.0],
       [31.0, 1, 249, 'Sales', 6.0],
       [26.0, 0, 841, 'Research & Development', 6.0],
       [58.0, 1, 147, 'Research & Development', 23.0],
       [19.0, 1, 528, 'Sales', 22.0],
       [22.0, 0, 594, 'Research & Development', 2.0],
       [49.0, 0, 470, 'Research & Development', 20.0],
       [43.0, 0, 957, 'Research & Development', 28.0],
       [50.0, 0, 809, 'Sales', 12.0],
       [31.0, 1, 542, 'Sales', 20.0],
       [41.0, 0, 802, 'Sales', 9.0],
       [26.0, 0, 1355, 'Human Resources', 25.0],
       [36.0, 0, 216, 'Research & Development', 6.0],
       [51.0, 1, 1150, 'Research & Development', 8.0],
       [39.0, 0, 1329, 'Sales', 4.0],
       [25.0, 0, 959, 'Sales', 28.0],
       [30.0, 0, 1240, 'Human Resources', 9.0],
       [35.0, 1, 1033, 'Research & Development', 9.0],
       [45.0, 0, 1316, 'Research & Development', 1.0],
       [38.0, 0, 364, 'Research & Development', 3.0],
       [30.0, 0, 438, 'Research & Development', 18.0]], dtype=object)

In [186]:
data.isnull().sum()

Age                        4
Attrition                  0
DailyRate                  0
Department                 2
DistanceFromHome           3
Education                  0
EmployeeCount              1
EmployeeNumber             1
EnvironmentSatisfaction    0
Gender                     4
HourlyRate                 3
dtype: int64

In [187]:
data.iloc[:,9:10]

     Gender
0    Female
1      Male
2      Male
3       NaN
4      Male
..      ...
139    Male
140  Female
141    Male
142  Female
143  Female

[144 rows x 1 columns]

In [189]:
imputer1 = SimpleImputer(missing_values = np.nan,strategy  = "most_frequent")

In [190]:
dataselection1 = imputer.fit_transform(data.iloc[:,9:10])

In [191]:
dataselection1

array([['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Male'],
       ['Female'],
       ['Female']], dtype=object)

In [192]:
#  For above 1 we use most_frequent because it is string

In [193]:
data = pd.read_csv("dataset/googleplaystore.csv")

In [194]:
data

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [195]:
data.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [200]:
#  fill data to  rating

dataloc=data.iloc[:,2:3]
dataloc

       Rating
0         4.1
1         3.9
2         4.7
3         4.5
4         4.3
...       ...
10836     4.5
10837     5.0
10838     NaN
10839     4.5
10840     4.5

[10841 rows x 1 columns]

In [201]:
imputer  = SimpleImputer(missing_values = np.nan, strategy = "mean") # average
dataselection2 = imputer.fit_transform(dataloc)

In [202]:
dataselection2

array([[4.1       ],
       [3.9       ],
       [4.7       ],
       ...,
       [4.19333832],
       [4.5       ],
       [4.5       ]])

In [ ]:
# So do it for all